### ISSUE TITLE
Can u make it support PathOfExile.exe (Standalone Version) plz?

### ISSUE THREAD

**Issue by solarkit22** [CrimsonED1/POE2loadingPainFix#2]
thanks a lot

**Comment by CrimsonED1** [comment]
Hey, this should be easy. I only Need 2 things. Can you give me, the exe file name, and the Client.txt (logfile) file location? The Steam Version has the Client.txt in maindir\log.

Have a nice rest christmas

**Comment by CrimsonED1** [comment]
i added support for standalone (version0.4), didnt know i can start both versions :)
Plz check if all is working as expected. With my system it does.

**Comment by solarkit22** [comment]
Thanks your fast response ， i will try it soon

**Comment by solarkit22** [comment]
it showing Waiting for exe: PathOfExileSteam/PathOfExile
seems not working
C:\Program Files (x86)\Grinding Gear Games\Path of Exile 2\PathOfExile.exe
C:\Program Files (x86)\Grinding Gear Games\Path of Exile 2\logs\Client.txt

**Comment by Peracutus** [comment]
same title with steam version
C:\Program Files (x86)\Steam\steamapps\common\Path of Exile 2\PathOfExile.exe
C:\Program Files (x86)\Steam\steamapps\common\Path of Exile 2\logs\Client.txt
![image](https://github.com/user-attachments/assets/73227262-78e4-4f40-b417-1da21c163083)

**Comment by CrimsonED1** [comment]
hey, i could not find an error. There must be an exception in the background thread. (in v0.4 they are ignored)
Tried both POE2 Editions again. Maybe its some right based on your machines.
I added a exception dialog in version 0.5 to track back where it occures. Plz send me the log from the exception dialog. (i need the line numbers ;)) 
**Example:**
![main_with_exception](https://github.com/user-attachments/assets/eca256ff-d5fc-4ca0-9283-9757e88c7a16)
![exception_dialog](https://github.com/user-attachments/assets/b7cf9f96-74a6-4bbe-a97d-201ffcc08558)

**Comment by CrimsonED1** [comment]
> same title with steam version C:\Program Files (x86)\Steam\steamapps\common\Path of Exile 2\PathOfExile.exe C:\Program Files (x86)\Steam\steamapps\common\Path of Exile 2\logs\Client.txt ![image](https://private-user-images.githubusercontent.com/74953662/398967162-73227262-78e4-4f40-b417-1da21c163083.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzNDQ1NzIsIm5iZiI6MTczNTM0NDI3MiwicGF0aCI6Ii83NDk1MzY2Mi8zOTg5NjcxNjItNzMyMjcyNjItNzhlNC00ZjQwLWI0MTctMWRhMjFjMTYzMDgzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDAwMDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOWJiNmY3YjJjYjA2ZWEwOTczN2YxOGMwNjQ0MGQ1MDZiMDQxYmNjZDg1MDA2ZDEwM2M5NjE5ZjkxZTk2OTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.HXk92K97Hl0jkwxJdBbAVdNaYl_geED4BHCL9PBmdzw)

and is this really **PathOfExile.exe** ? 
My POE2-Steam Looks like this:

![image](https://github.com/user-attachments/assets/3cf14fc0-ec21-4761-bf69-b868e7a9a0ca)

**Comment by CrimsonED1** [comment]
if done some additional changes, that may result to better behavior in this issue (verison0.6):
https://github.com/CrimsonED1/POE2loadingPainFix/releases/tag/version0.6

**Comment by Peracutus** [comment]
CPU: 11
Version: 8.0.11
IsPrivilegedProcess: False
Is64BitOperatingSystem: True
Is64BitProcess: True
OSVersion: Microsoft Windows NT 10.0.26100.0
---------------------
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at POE2loadingPainFix.CpuTools.GetProcessorAffinity(IEnumerable`1 target) in .\POE2loadingPainFix\POE2loadingPainFix\CpuTools.cs:line 25
   at POE2loadingPainFix.CpuThrottleDiskusage.Throttler.Thread_Execute_Sub() in .\POE2loadingPainFix\POE2loadingPainFix\CpuThrottleDiskusage\Throttler.cs:line 333
   at POE2loadingPainFix.CpuThrottleDiskusage.Throttler.Thread_Execute(Object sender) in .\POE2loadingPainFix\POE2loadingPainFix\CpuThrottleDiskusage\Throttler.cs:line 144
---------------------

> hey, i could not find an error. There must be an exception in the background thread. (in v0.4 they are ignored) Tried both POE2 Editions again. Maybe its some right based on your machines. I added a exception dialog in version 0.5 to track back where it occures. Plz send me the log from the exception dialog. (i need the line numbers ;)) **Example:** ![main_with_exception](https://private-user-images.githubusercontent.com/41068599/399025430-eca256ff-d5fc-4ca0-9283-9757e88c7a16.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTQxMDMsIm5iZiI6MTczNTM5MzgwMywicGF0aCI6Ii80MTA2ODU5OS8zOTkwMjU0MzAtZWNhMjU2ZmYtZDVmYy00Y2EwLTkyODMtOTc1N2U4OGM3YTE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDEzNTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyNzUyNGRhN2YzNjg5N2MxZjM5NTgyZWQ2NDY0ZTFmMzI3YjhiNDc0YzhhYzVmOGZhY2E3NDA5Mzg1NjdmZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XfW5F9Em1hY26x5miE_Xaldy7FyXMurezenhD0Q4hu8) ![exception_dialog](https://private-user-images.githubusercontent.com/41068599/399025432-b7cf9f96-74a6-4bbe-a97d-201ffcc08558.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUzOTQxMDMsIm5iZiI6MTczNTM5MzgwMywicGF0aCI6Ii80MTA2ODU5OS8zOTkwMjU0MzItYjdjZjlmOTYtNzRhNi00YmJlLWE5N2QtMjAxZmZjYzA4NTU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI4VDEzNTAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZjQ0NGU2YTliNDhkOWZmMzYzZTgyODUyMjc0YmU0YTExNDBjYTIxMGQ5NDgyNjEwM2Q2YmQzZGUzMDI4YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.XvJHGn1t2N_dN895mD6_9l4j5z7-dY7sMX9QejlcKiI)

**Comment by CrimsonED1** [comment]
> ## CPU: 11
> Version: 8.0.11
> IsPrivilegedProcess: False
> Is64BitOperatingSystem: True
> Is64BitProcess: True
> OSVersion: Microsoft Windows NT 10.0.26100.0
> ## System.IndexOutOfRangeException: Index was outside the bounds of the array.
> at POE2loadingPainFix.CpuTools.GetProcessorAffinity(IEnumerable`1 target) in .\POE2loadingPainFix\POE2loadingPainFix\CpuTools.cs:line 25
> at POE2loadingPainFix.CpuThrottleDiskusage.Throttler.Thread_Execute_Sub() in .\POE2loadingPainFix\POE2loadingPainFix\CpuThrottleDiskusage\Throttler.cs:line 333
> at POE2loadingPainFix.CpuThrottleDiskusage.Throttler.Thread_Execute(Object sender) in .\POE2loadingPainFix\POE2loadingPainFix\CpuThrottleDiskusage\Throttler.cs:line 144


ok i fixed this. (in version 0.7).
i hope this was the same bug the other authors had.
The problem was the **11 processors**. I didnt know odds are possible XD
(.NET api was only talking about 4 per core)
Ive added testing for several comibations of cpus, but it should be save now.
It always returns a min of 1 processor for affinity. 
![image](https://github.com/user-attachments/assets/fa9d168d-c752-450d-935c-3589dcb7ae15)


i also added cpu infos, which are also included into the exception window, if there are more bugs:
![image](https://github.com/user-attachments/assets/03e8fa11-51b0-48a8-ab79-421b96a147d5)

thx for reporting. And i hope it runs now ;)
